apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/app

images:
  - name: 140858350811.dkr.ecr.ap-south-1.amazonaws.com/exploreexpeditionsapp
    newTag: v1.0.29-dev

replicas:
  - name: two-tier-app
    count: 1