apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - secrets.yaml
  - secret_store.yaml
  - external_secret.yaml
  - configmap.yaml
  - rollout.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
